app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("basicSpotThenDOEThenSPOT")

app$setInputs(tabs = "spotConfig")
try(app$setInputs(tabs = "runMode"), silent = T)
app$setInputs(runSpotIter = "click")
app$setInputs(tabs = "spotConfig")
try(app$setInputs(tabs = "runMode"), silent = T)
app$setInputs(runCreateDOE = "click")
app$setInputs(evaluateData = "click")
app$setInputs(runSpotIter = "click")
app$snapshot(list(output = "resultTable"))
