app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("testSmoofBirdFunction")

app$setInputs(objectiveFunction = "smoof")
app$setInputs(smoofFunctionSelector = "Bird")
app$setInputs(addDimension = "click")
app$setInputs(tabs = "spotConfig")
try(app$setInputs(tabs = "runMode"), silent = T)
app$setInputs(runSpotIter = "click")
app$setInputs(tabs = "objectiveFunction")
app$setInputs(removeDimension6 = "click")
try(app$setInputs(tabs = "runMode"), silent = T)
app$setInputs(runSpotIter = "click")
app$snapshot(list(output = "resultTable"))
