app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("testGenoud4DimRF")

app$setInputs(addDimension = "click")
app$setInputs(dimensionType2 = "integer")
app$setInputs(dimensionAmount2 = 2)
app$setInputs(tabs = "spotConfig")
app$setInputs(optimizerSelector = "optimGenoud")
app$setInputs(xml_optimGenoudcontrol = TRUE)
app$setInputs(xml_optimGenoudcontrolpopulationSize = 40)
app$setInputs(xml_optimGenoudcontrolfunEvals = 200)
app$setInputs(modelSelector = "buildRandomForest")
try(app$setInputs(tabs = "runMode"), silent = T)
app$setInputs(runSpotIter = "click",wait_=FALSE, values_=FALSE)
app$setInputs(runCreateDOE = "click",wait_=FALSE, values_=FALSE)
app$setInputs(evaluateData = "click",wait_=FALSE, values_=FALSE)
app$setInputs(proposeNewPoint = "click",wait_=FALSE, values_=FALSE)
app$setInputs(evaluateData = "click",wait_=FALSE, values_=FALSE)
app$setInputs(selectorXAUTO = "X4",wait_=FALSE, values_=FALSE)
app$snapshot(list(output = "resultTable"))

