app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("testWrongInputCreateDOE")


app$setInputs(tabs = "spotConfig")
app$setInputs(tabs = "objectiveFunction")
app$setInputs(tabs = "spotConfig")
app$setInputs(xml_designLHDcontrol = TRUE)
app$setInputs(xml_designLHDcontrolsize = "cflbre")
try(app$setInputs(tabs = "runMode"), silent = T)
app$setInputs(runCreateDOE = "click")
app$setInputs(tabs = "spotConfig")
app$setInputs(xml_designLHDcontrolsize = 10)
try(app$setInputs(tabs = "runMode"), silent = T)
app$setInputs(runCreateDOE = "click")
app$snapshot(list(output = "resultTable"))
