app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("testWrongInputProposeNewPoint")

app$setInputs(tabs = "spotConfig")
app$setInputs(tabs = "runMode")
app$setInputs(runCreateDOE = "click")
app$setInputs(evaluateData = "click")
app$setInputs(tabs = "spotConfig")
app$setInputs(xml_optimLHDcontrol = TRUE)
app$setInputs(xml_optimLHDcontrolfunEvals = "chara")
app$setInputs(tabs = "runMode")
app$setInputs(proposeNewPoint = "click")
app$snapshot(list(output = "resultTable"))
