app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("testWrongEnvironmentFunction")

app$setInputs(objectiveFunction = "rEnv")
app$setInputs(funName = "unknownFunctionForTestingPurpose")
app$setInputs(addDimension = "click")
app$setInputs(addDimension = "click")
app$setInputs(dimensionAmount3 = 2)
app$setInputs(lowerBound3 = -4)
app$setInputs(tabs = "spotConfig")
app$setInputs(tabs = "runMode")
app$setInputs(runSpotIter = "click")
app$setInputs(tabs = "objectiveFunction")
app$setInputs(funName = "branin")
app$setInputs(tabs = "spotConfig")
app$setInputs(tabs = "runMode")
app$setInputs(runSpotIter = "click")
Sys.sleep(10)
app$snapshot(list(output = "resultTable"))
